REM   Script: script-criacao-tabelas
REM   Script DDL para criação das tabelas do projeto

CREATE TABLE CONSTRUTORAS (
    codigo          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    nome            VARCHAR2(100) NOT NULL,
    nome_fantasia   VARCHAR2(100),
    email           VARCHAR2(100),
    CONSTRAINT pk_construtoras PRIMARY KEY (codigo),
    CONSTRAINT uq_construtoras_email UNIQUE (email)
);

CREATE TABLE TELEFONES (
    codigo_construtora  NUMBER NOT NULL,
    numero              VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_telefones PRIMARY KEY (codigo_construtora, numero),
    CONSTRAINT fk_telefones_construtoras FOREIGN KEY (codigo_construtora)
        REFERENCES CONSTRUTORAS (codigo)
        ON DELETE CASCADE
);

CREATE TABLE CATEGORIAS (
    codigo      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    descricao   VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_categorias PRIMARY KEY (codigo)
);

CREATE TABLE EQUIPAMENTOS (
    codigo              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    nome                VARCHAR2(100) NOT NULL,
    valor_uso_diario    NUMBER(10, 2) NOT NULL,
    codigo_categoria    NUMBER NOT NULL,
    CONSTRAINT pk_equipamentos PRIMARY KEY (codigo),
    CONSTRAINT fk_equipamentos_categorias FOREIGN KEY (codigo_categoria)
        REFERENCES CATEGORIAS (codigo)
);

CREATE TABLE OBRAS (
    codigo              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    nome                VARCHAR2(100) NOT NULL,
    logradouro          VARCHAR2(200) NOT NULL,
    numero              VARCHAR2(10) NOT NULL,
    complemento         VARCHAR2(100),
    codigo_construtora  NUMBER NOT NULL,
    CONSTRAINT pk_obras PRIMARY KEY (codigo),
    CONSTRAINT fk_obras_construtoras FOREIGN KEY (codigo_construtora)
        REFERENCES CONSTRUTORAS (codigo)
);

CREATE TABLE TRABALHADORES (
    cpf         CHAR(11) NOT NULL,
    nome        VARCHAR2(100) NOT NULL,
    salario     NUMBER(10, 2) NOT NULL,
    codigo_obra NUMBER NOT NULL,
    CONSTRAINT pk_trabalhadores PRIMARY KEY (cpf),
    CONSTRAINT fk_trabalhadores_obras FOREIGN KEY (codigo_obra)
        REFERENCES OBRAS (codigo)
);

CREATE TABLE ALOCACAO (
    codigo_obra         NUMBER NOT NULL,
    codigo_equipamento  NUMBER NOT NULL,
    data_inicio         DATE NOT NULL,
    data_termino        DATE NOT NULL,
    CONSTRAINT pk_alocacao PRIMARY KEY (codigo_obra, codigo_equipamento),
    CONSTRAINT fk_alocacao_obras FOREIGN KEY (codigo_obra)
        REFERENCES OBRAS (codigo),
    CONSTRAINT fk_alocacao_equipamentos FOREIGN KEY (codigo_equipamento)
        REFERENCES EQUIPAMENTOS (codigo)
);

